### ISSUE TITLE
Optional elements with the same default position

### ISSUE THREAD

**Issue by nboldi** [nboldi/haskell-tools#12]
For example, when adding qualification and context to 
```
instance C (A x) where
```
it should became
```
instance forall x . Show x => C (A x) where
```
and not 
```
instance Show x => forall x . C (A x) where
```
although both the qualification and the context is after the `instance` keyword. In these cases the elements should be inserted in the order they are in the datatype definition.

**Comment by nboldi** [comment]
This is automatically archieved via the transformation algorithm

**Comment by kelemzol** [comment]
:D:D::D:D:D:D:D:D:D:D:D:D
http://9gag.com/gag/a3BAOmm


2016 Március 4, Péntek 14:45 CET dátummal, Boldizsár Németh <notifications@github.com> ezt írta:
 
This is automatically archieved via the transformation algorithm
