### ISSUE TITLE
Complete transformation from GHC to representation

### ISSUE THREAD

**Issue by nboldi** [nboldi/haskell-tools#9]
These missing features cause errors when used

Missing features:
  - ~~standalone derivings~~
  - ~~data and type family instances~~
  - ~~pattern synonym type signature~~
  - ~~rewrite rules~~
  - ~~role annotations~~
  - ~~arrow expressions~~
  - ~~static expressions~~
  - N plus K patterns
  - Copatterns
  - Template haskell splices, brackets, quasi-quotation

Most of the missing features are commented where they should be handled.

**Comment by kelemzol** [comment]
<interactive>: Language\Haskell\Tools\AST\FromGHC\Stmts.hs:(31,1)-(34,93): Non-e
xhaustive patterns in function trfDoStmt'

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

module Test where

import Data.Maybe
import qualified Data.List as L

main :: IO ()
main = do
    putStrLn $ L.map id $ "Hello Demo"

type Number = Integer
type Name = String

class Elem a where
    op :: a -> a -> a
    cond :: a -> Bool

instance Elem Int where
    op = (+)
    cond = (>0)

data Req a = Req
    { elem1 :: Int
    , elem2 :: a
    }
  deriving (Eq, Ord, Show)

**Comment by kelemzol** [comment]
~~~~~~~~~~~~~~~~
<interactive>: Language\Haskell\Tools\AST\FromGHC\Types.hs:(30,1)-(55,72): Non-e
xhaustive patterns in function trfType'
~~~~~~~~~~~~~~~~~~

module Test where

import Data.Maybe
import qualified Data.List as L

main :: IO ()
main = putStrLn $ L.map id $ "Hello Demo"

**Comment by nboldi** [comment]
Solved these two problems
